// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.swinchester.roo.quickstarts.changelog.web;

import org.springframework.beans.factory.annotation.Configurable;
import org.swinchester.roo.quickstarts.changelog.web.PersonBean;

privileged aspect PersonBean_Roo_Configurable {
    
    declare @type: PersonBean: @Configurable;
    
}
