// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.swinchester.roo.quickstarts.changelog;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessedDataOnDemand;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessedIntegrationTest;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessedRepository;

privileged aspect CamelLastEventProcessedIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CamelLastEventProcessedIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CamelLastEventProcessedIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CamelLastEventProcessedIntegrationTest: @Transactional;
    
    @Autowired
    CamelLastEventProcessedDataOnDemand CamelLastEventProcessedIntegrationTest.dod;
    
    @Autowired
    CamelLastEventProcessedRepository CamelLastEventProcessedIntegrationTest.camelLastEventProcessedRepository;
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", dod.getRandomCamelLastEventProcessed());
        long count = camelLastEventProcessedRepository.count();
        Assert.assertTrue("Counter for 'CamelLastEventProcessed' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testFind() {
        CamelLastEventProcessed obj = dod.getRandomCamelLastEventProcessed();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to provide an identifier", id);
        obj = camelLastEventProcessedRepository.findOne(id);
        Assert.assertNotNull("Find method for 'CamelLastEventProcessed' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CamelLastEventProcessed' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", dod.getRandomCamelLastEventProcessed());
        long count = camelLastEventProcessedRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'CamelLastEventProcessed', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CamelLastEventProcessed> result = camelLastEventProcessedRepository.findAll();
        Assert.assertNotNull("Find all method for 'CamelLastEventProcessed' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CamelLastEventProcessed' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", dod.getRandomCamelLastEventProcessed());
        long count = camelLastEventProcessedRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CamelLastEventProcessed> result = camelLastEventProcessedRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'CamelLastEventProcessed' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CamelLastEventProcessed' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testFlush() {
        CamelLastEventProcessed obj = dod.getRandomCamelLastEventProcessed();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to provide an identifier", id);
        obj = camelLastEventProcessedRepository.findOne(id);
        Assert.assertNotNull("Find method for 'CamelLastEventProcessed' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCamelLastEventProcessed(obj);
        Integer currentVersion = obj.getVersion();
        camelLastEventProcessedRepository.flush();
        Assert.assertTrue("Version for 'CamelLastEventProcessed' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testSaveUpdate() {
        CamelLastEventProcessed obj = dod.getRandomCamelLastEventProcessed();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to provide an identifier", id);
        obj = camelLastEventProcessedRepository.findOne(id);
        boolean modified =  dod.modifyCamelLastEventProcessed(obj);
        Integer currentVersion = obj.getVersion();
        CamelLastEventProcessed merged = camelLastEventProcessedRepository.save(obj);
        camelLastEventProcessedRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CamelLastEventProcessed' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", dod.getRandomCamelLastEventProcessed());
        CamelLastEventProcessed obj = dod.getNewTransientCamelLastEventProcessed(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CamelLastEventProcessed' identifier to be null", obj.getId());
        try {
            camelLastEventProcessedRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        camelLastEventProcessedRepository.flush();
        Assert.assertNotNull("Expected 'CamelLastEventProcessed' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CamelLastEventProcessedIntegrationTest.testDelete() {
        CamelLastEventProcessed obj = dod.getRandomCamelLastEventProcessed();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CamelLastEventProcessed' failed to provide an identifier", id);
        obj = camelLastEventProcessedRepository.findOne(id);
        camelLastEventProcessedRepository.delete(obj);
        camelLastEventProcessedRepository.flush();
        Assert.assertNull("Failed to remove 'CamelLastEventProcessed' with identifier '" + id + "'", camelLastEventProcessedRepository.findOne(id));
    }
    
}
