// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.swinchester.roo.quickstarts.changelog;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessed;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessedDataOnDemand;
import org.swinchester.roo.quickstarts.changelog.CamelLastEventProcessedRepository;

privileged aspect CamelLastEventProcessedDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CamelLastEventProcessedDataOnDemand: @Component;
    
    private Random CamelLastEventProcessedDataOnDemand.rnd = new SecureRandom();
    
    private List<CamelLastEventProcessed> CamelLastEventProcessedDataOnDemand.data;
    
    @Autowired
    CamelLastEventProcessedRepository CamelLastEventProcessedDataOnDemand.camelLastEventProcessedRepository;
    
    public CamelLastEventProcessed CamelLastEventProcessedDataOnDemand.getNewTransientCamelLastEventProcessed(int index) {
        CamelLastEventProcessed obj = new CamelLastEventProcessed();
        setEventId(obj, index);
        return obj;
    }
    
    public void CamelLastEventProcessedDataOnDemand.setEventId(CamelLastEventProcessed obj, int index) {
        Long eventId = new Integer(index).longValue();
        obj.setEventId(eventId);
    }
    
    public CamelLastEventProcessed CamelLastEventProcessedDataOnDemand.getSpecificCamelLastEventProcessed(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CamelLastEventProcessed obj = data.get(index);
        Long id = obj.getId();
        return camelLastEventProcessedRepository.findOne(id);
    }
    
    public CamelLastEventProcessed CamelLastEventProcessedDataOnDemand.getRandomCamelLastEventProcessed() {
        init();
        CamelLastEventProcessed obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return camelLastEventProcessedRepository.findOne(id);
    }
    
    public boolean CamelLastEventProcessedDataOnDemand.modifyCamelLastEventProcessed(CamelLastEventProcessed obj) {
        return false;
    }
    
    public void CamelLastEventProcessedDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = camelLastEventProcessedRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CamelLastEventProcessed' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CamelLastEventProcessed>();
        for (int i = 0; i < 10; i++) {
            CamelLastEventProcessed obj = getNewTransientCamelLastEventProcessed(i);
            try {
                camelLastEventProcessedRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            camelLastEventProcessedRepository.flush();
            data.add(obj);
        }
    }
    
}
