// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.swinchester.roo.quickstarts.changelog;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.swinchester.roo.quickstarts.changelog.EventLogDataOnDemand;
import org.swinchester.roo.quickstarts.changelog.EventLogIntegrationTest;
import org.swinchester.roo.quickstarts.changelog.EventLogRepository;

privileged aspect EventLogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventLogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventLogIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EventLogIntegrationTest: @Transactional;
    
    @Autowired
    EventLogDataOnDemand EventLogIntegrationTest.dod;
    
    @Autowired
    EventLogRepository EventLogIntegrationTest.eventLogRepository;
    
    @Test
    public void EventLogIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", dod.getRandomEventLog());
        long count = eventLogRepository.count();
        Assert.assertTrue("Counter for 'EventLog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventLogIntegrationTest.testFind() {
        EventLog obj = dod.getRandomEventLog();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", obj);
        Long id = obj.getRecordId();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to provide an identifier", id);
        obj = eventLogRepository.findOne(id);
        Assert.assertNotNull("Find method for 'EventLog' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EventLog' returned the incorrect identifier", id, obj.getRecordId());
    }
    
    @Test
    public void EventLogIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", dod.getRandomEventLog());
        long count = eventLogRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'EventLog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EventLog> result = eventLogRepository.findAll();
        Assert.assertNotNull("Find all method for 'EventLog' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EventLog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventLogIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", dod.getRandomEventLog());
        long count = eventLogRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EventLog> result = eventLogRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'EventLog' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EventLog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventLogIntegrationTest.testFlush() {
        EventLog obj = dod.getRandomEventLog();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", obj);
        Long id = obj.getRecordId();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to provide an identifier", id);
        obj = eventLogRepository.findOne(id);
        Assert.assertNotNull("Find method for 'EventLog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEventLog(obj);
        Integer currentVersion = obj.getVersion();
        eventLogRepository.flush();
        Assert.assertTrue("Version for 'EventLog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventLogIntegrationTest.testSaveUpdate() {
        EventLog obj = dod.getRandomEventLog();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", obj);
        Long id = obj.getRecordId();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to provide an identifier", id);
        obj = eventLogRepository.findOne(id);
        boolean modified =  dod.modifyEventLog(obj);
        Integer currentVersion = obj.getVersion();
        EventLog merged = eventLogRepository.save(obj);
        eventLogRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getRecordId(), id);
        Assert.assertTrue("Version for 'EventLog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventLogIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", dod.getRandomEventLog());
        EventLog obj = dod.getNewTransientEventLog(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EventLog' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EventLog' identifier to be null", obj.getRecordId());
        try {
            eventLogRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        eventLogRepository.flush();
        Assert.assertNotNull("Expected 'EventLog' identifier to no longer be null", obj.getRecordId());
    }
    
    @Test
    public void EventLogIntegrationTest.testDelete() {
        EventLog obj = dod.getRandomEventLog();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to initialize correctly", obj);
        Long id = obj.getRecordId();
        Assert.assertNotNull("Data on demand for 'EventLog' failed to provide an identifier", id);
        obj = eventLogRepository.findOne(id);
        eventLogRepository.delete(obj);
        eventLogRepository.flush();
        Assert.assertNull("Failed to remove 'EventLog' with identifier '" + id + "'", eventLogRepository.findOne(id));
    }
    
}
